name: "Setup Juju on microk8s"
description: "An action to setup and bootstrap Juju on microk8s"

runs:
  using: "composite"
  steps:
    - name: setup microk8s
      uses: balchua/microk8s-actions@v0.2.2
      with:
        channel: "${{ matrix.microk8s }}"
        addons: '["dns", "hostpath-storage", "ingress"]'
    - name: Install Dependencies
      shell: bash
      run: |
        set -euxo pipefail
        sudo snap install juju --classic
    - name: bootstrap juju
      shell: bash
      run: |
        sg microk8s <<EOF
          set -eux
          microk8s kubectl wait --for=condition=available -nkube-system deployment/coredns deployment/hostpath-provisioner --timeout=10m
          juju bootstrap microk8s --debug uk8s --config test-mode=true --model-default test-mode=true
        EOF
