# Terraform Provider testing workflow using different terraform versions
# and clouds.
name: Unit Tests

# This GitHub action runs your tests for each pull request.
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  #    paths-ignore:
  #     DON'T SET - these are "required" so they need to run on every PR
  push:
    branches:
      - "main"

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

jobs:
  # Ensure project builds before running unit tests
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - run: go build -v .

  # Run internal/juju unit tests
  test:
    name: Juju unit tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true
      - run: make juju-unit-test
